import Footer from "@/components/Footer";
import Header from "@/components/Header";
import "./globals.css";
import { Roboto_Flex } from "next/font/google";
import ClientProviders from "@/components/ClientProviders";

const inter = Roboto_Flex({
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${inter.className} dark`}>
      <body className="flex flex-col w-full min-h-screen">
        <ClientProviders>
          <Header />
          {children}
          <Footer />
        </ClientProviders>
      </body>
    </html>
  );
}
