//Generated by CreateModelInterfaceFile
//Generated by GetCompleteModelInterface
import { ListQuery } from "./interface";

export interface PostBody {
  postId: number;
  userId: string;
  title: string;
  body: string;
}

export interface PostQuery extends ListQuery {}

export interface PostBodyForUpdate extends PostBody {}
